config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "hearts#index"
  resources :hearts do
    resources :comments, only: [:new, :create]
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '好きなこと' },
    { id: 3, name: '得意なこと' },
    { id: 4, name: '重要なこと' },
    { id: 5, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :hearts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :heart
end

app/models/heart.rb
class Heart < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user

  with_options presence: true do
    validates :title
    validates :detail
    validates :category_id, numericality: { other_than: 1 }
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :heart
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hearts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_hearts, through: :likes, source: :heart

  with_options presence: true do
    validates :nickname
    validates :email, uniqueness: true, format: { with: /@/, message: "は@を含めて入力して下さい" }
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+{6,}\z/i, message: "は半角英数字6文字以上で入力して下さい"}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comments = Comment.all
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    heart = Heart.find(params[:heart_id])
    user_name = current_user.nickname
    if @comment.save
      ActionCable.server.broadcast 'comment_channel', content: @comment, heart: heart, user_name: user_name
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, heart_id: params[:heart_id])
  end
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
  before_action :move_to_sign_in, only: [:new]
  before_action :set_heart, only: [:show, :edit, :update]
  def index
    @hearts = Heart.all
  end

  def new
    @heart = Heart.new
  end

  def create
    @heart = Heart.new(heart_params)
    if @heart.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @heart.comments.includes(:user)
  end

  def edit
  end

  def update
    if @heart.update(heart_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    heart = Heart.find(params[:id])
    heart.destroy
    redirect_to root_path
  end
  private
  def move_to_sign_in
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def heart_params
    params.require(:heart).permit(:title, :detail, :category_id).merge(user_id: current_user.id)
  end

  def set_heart
    @heart = Heart.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_heart

  def create
    @like = Like.new(user_id: current_user.id, heart_id: @heart.id)
    @like.save
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, heart_id: @heart.id)
    @like.destroy
  end

  private
  def set_heart
    @heart = Heart.find_by(id: params[:heart_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @email = current_user.email
    @hearts = current_user.hearts
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hearts/edit.html.erb
<%= render "shared/header" %>
<main class="main">
  <div class="sign-up-box">
    <%= form_with model: @heart, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

      <div>
        <%= f.label "タイトル" %><br />
        <%= f.text_field :title, class: "sign-up-box-list", placeholder: "タイトルを入力してください" %>
      </div>
      <div>
        <%= f.label "カテゴリー" %><br />
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"sign-up-box-list"}) %>
      </div>
      <div>
        <%= f.label "子カテゴリー" %><br />
        <%= f.text_field :category_id, class: "sign-up-box-list", placeholder: "子カテゴリーを選択してください" %>
      </div>
      <div>
        <%= f.label "あなたのことを教えて下さい♪" %><br />
        <%= f.text_area :detail, class: "sign-up-box-list", placeholder: "あなたの想いを自由に書いてください" %>
      </div>
      <div class="button">
        <%= f.submit "編集完了", class: "sign-up-button" %>
      </div>
    <% end %>
  </div>
</main>
<%= render "shared/footer" %>

app/views/hearts/index.html.erb
<%= render "shared/header" %>
<div class="search-box">
  <input type="text" class="search-text">
  <div class="search-button">
    <span><a href="#">検索</a></span>
  </div>
</div>
<main>
  <div class="main">
    <div class="category">
      <ul class="category-lists">
        <a href="#"><li class="category-list">全カテゴリー</li></a>
        <a href="#"><li class="category-list">好きなこと</li></a>
        <a href="#"><li class="category-list">得意なこと</li></a>
        <a href="#"><li class="category-list">重要なこと</li></a>
        <a href="#"><li class="category-list">その他</li></a>
      </ul>
    </div>
    <div class="hearts">
      <ul>
        <% @hearts.each do |heart| %>
          <%= link_to heart_path(heart.id), method: :get do %>
          <li class="heart-list">
            <div class="heart-list-main">
              <p class="heart-title"><%= heart.title %>      <span class="good-point">⭐️<%= heart.likes.count %></span></p>
              <p class="heart-child-category"><%= heart.category.name %></p>
            </div>
            <p class="heart-nickname"><%= heart.user.nickname %></p>
          </li>
          <% end %>
        <% end %>
      
        <% if @hearts.blank? %>
          <a href="#">
            <li class="heart-list">
              <div class="heart-list-main">
                <p class="heart-title">タイトル</p>
                <p class="heart-child-category">子カテゴリー</p>
              </div>
              <p class="heart-nickname">投稿者名</p>
            </li>
          </a>
        <% end %>
      </ul>
    </div>
  </div>
  <a href="/hearts/new">
    <div class='purchase-btn'>投稿する
    </div>
  </a>
</main>
<%= render "shared/footer" %>

app/views/hearts/new.html.erb
<%= render "shared/header" %>
<main class="main">
  <div class="sign-up-box">
    <%= form_with model: @heart, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    
      <div>
        <%= f.label "タイトル" %><br />
        <%= f.text_field :title, class: "sign-up-box-list", placeholder: "タイトルを入力してください" %>
      </div>
      <div>
        <%= f.label "カテゴリー" %><br />
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"sign-up-box-list"}) %>
      </div>
      <div>
        <%= f.label "子カテゴリー" %><br />
        <%= f.text_field :category_id, class: "sign-up-box-list", placeholder: "子カテゴリーを選択してください" %>
      </div>
      <div>
        <%= f.label "あなたのことを教えて下さい♪" %><br />
        <%= f.text_area :detail, class: "sign-up-box-list", placeholder: "(例)人と話すことが大好きです！" %>
      </div>
      <div class="button">
        <%= f.submit "投稿する", class: "sign-up-button" %>
      </div>
    <% end %>
  </div>
</main>
<%= render "shared/footer" %>

app/views/hearts/show.html.erb
<%= render "shared/header" %>
<main class="main">
  <div class="sign-up-box">
    <div>
      <p>タイトル：<%= @heart.title %></p>
    </div>
    <div>
      <p>カテゴリー：<%= @heart.category.name %></p>
    </div>
    <div>
      <p>子カテゴリー</p>
    </div>
    <div>
      <p>&lt;あなたのことを教えて下さい♪&gt;</p>
      <p><%= @heart.detail %></p>
    </div>
    <div class="stamp">
      <div></div>
      <div id="likes_buttons_<%= @heart.id %>">
        <%= render partial: 'likes/like', locals: { heart: @heart } %>
      </div>
    </div>
    <div class="comment">
      <div class="comment-box" id="comments">
        <% if @comments %>
          <% @comments.reverse_each do |comment| %>
            <% if @heart.user_id == comment.user_id %>
              <div class="comment-text">
                <p>☆<%= comment.user.nickname %></p>
                <p><%= comment.text %></p>
              </div>
            <% else %>
              <div class="comment-text-another">
                <p><%= comment.user.nickname %></p>
                <p><%= comment.text %></p>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="comment-input">
      <% if user_signed_in? && current_user.id == @heart.user.id %>
        <%= form_with(model: [@heart, @comment], local: true) do |f| %>
          <div><%= f.text_area :text, placeholder: "コメントする", class: "comment-input-box", id: "comment-input-box" %></div>
          <div>
            <%= button_tag type: :submit, class: "comment-button", id: "comment-button" do %>
              <p>コメントする</p>
            <% end %>
          </div>
        <% end %>
      <% elsif user_signed_in? %>
        <%= form_with(model: [@heart, @comment], local: true) do |f| %>
          <div><%= f.text_field :text, value: "もっと聞きたい！", class: "comment-input-box", id: "motto_button"%></div>
          <div>
            <%= button_tag type: :submit, class: "comment-button" do %>
              <p>もっと聞きたい！</p>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <% unless user_signed_in? %>
        <button class="comment-button">もっと聞きたい！</button>
        <p>※※※ "もっと聞きたい！"には新規登録/ログインが必要です ※※※</p>
      <% end %>
    </div>
    <% if user_signed_in? && current_user.id == @heart.user.id %>
    <div class="menu-button">
      <%= link_to '編集する', edit_heart_path(@heart.id), method: :get, class: "edit-button" %>
      <%= link_to '削除する', heart_path(@heart.id), method: :delete, class: "edit-button" %>
    </div>
    <% end %>
  </div>
</main>
<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OriginalApp28168</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if Like.exists?(user_id: current_user.id, heart_id: heart.id) %>
    <%= link_to heart_likes_path(@heart.id), method: :delete, remote: true do %>
      <p class="stamp-good like">いいね！⭐️<%= @heart.likes.count %></p>
    <% end %>
  <% else %>
    <%= link_to heart_likes_path(@heart.id), method: :post, remote: true do %>
      <p class="stamp-good">いいね！⭐️<%= @heart.likes.count %></p>
    <% end %>
  <% end %>
<% else %>
  <p class="stamp-good">いいね！⭐️<%= @heart.likes.count %></p>
<% end %>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @heart.id %>').html("<%= j(render partial: 'likes/like', locals: {heart: @heart}) %>");

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @heart.id %>').html("<%= j(render partial: 'likes/like', locals: {heart: @heart}) %>");

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p>著作権</p>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header">
    <a href="/">
      <div class="header-logo">
        <p class="main-logo">Heart Share</p>
      </div>
    </a>
    <div class="header-menu">
      <div class="user-menu">
        <% if user_signed_in? %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "user-menu-list" %>
          <%= link_to current_user.nickname, "/users/#{current_user.id}", class: "user-menu-list" %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "user-menu-list" %>
          <%= link_to "新規登録", new_user_registration_path, class: "user-menu-list" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="header-string">
    <p>
      自分の想っていることをアウトプットして、<br>
      やりたいことを具体化していこう♪
      アウトプットしている記事を参考にして、<br>
      新しい考えも取り入れよう♪
    </p>
  </div>
</header>

app/views/users/show.html.erb
<%= render "shared/header" %>
<main class="main">
  <div class="sign-up-box">
    <div>
      <P>ニックネーム：<%= @nickname %></p>
    </div>
    <div>
      <p>Email：<%= @email %></p>
    </div>
    <div>
      <p>&lt; 投稿した記事一覧 &gt;</p>
      <ul>
        <% @hearts.each do |heart| %>
          <%= link_to heart_path(heart.id), method: :get do %>
          <li class="heart-list">
            <div class="heart-list-main">
              <p class="heart-title"><%= heart.title %>      <span class="good-point">⭐️<%= heart.likes.count %></span></p>
              <p class="heart-child-category"><%= heart.category.name %></p>
            </div>
            <p class="heart-nickname"><%= heart.user.nickname %></p>
          </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</main>
<%= render "shared/footer" %>